spool C:\2_sifilis.csv
set sqlformat csv
set heading off
set FEEDBACK OFF
set ECHO OFF


SELECT DISTRITO
      ,UNIDADE
      ,AREA
      ,EXTRACT(YEAR FROM DATA_NOTIF) AS ANO
      ,EXTRACT(MONTH FROM DATA_NOTIF) AS MES
      ,COUNT(DISTINCT(USUARIO)) PESSOAS_SIFILIS
      ,COUNT(DISTINCT(CASE WHEN (BENZETA1 + BENZETA2 + BENZETA3 >= 1) THEN USUARIO END)) AS PESSOAS_TTO
      
FROM 
( 
SELECT DISTRITO
      ,UNIDADE
      ,AREA
      ,USUARIO
      ,DATA_NOTIF
      ,COUNT(CASE WHEN PROC1 = '90019' THEN USUARIO END) AS BENZETA1
      ,COUNT(CASE WHEN PROC2 = '90019' THEN USUARIO END) AS BENZETA2
      ,COUNT(CASE WHEN PROC3 = '90019' THEN USUARIO END) AS BENZETA3
      
  

FROM (

SELECT REG.NM_REGIAO AS DISTRITO
      ,UNI.NM_UNIDADE AS UNIDADE
      ,LGR.CD_AREA AS AREA
      ,CON.CD_CONSULTA AS CONSULTA
      ,CON.CD_USUARIO AS USUARIO
      ,CON.DT_AGENDA AS DIA_CONSULTA
      ,NOF.CD_CID AS CID_NOTIF
      ,NOF.DT_NOTIFICACAO AS DATA_NOTIF
      ,CON.CD_PROCEDIMENTO AS PROC1
      ,OUC.CD_PROCEDIMENTO AS PROC2
      ,PMT.CD_PROCEDIMENTO_BPA AS PROC3

            
      
FROM VIP_NOTIFICA_FICHA NOF
LEFT JOIN VIA_CONSULTA CON ON CON.CD_USUARIO = NOF.CD_USUARIO
LEFT JOIN VIP_OUTRA_CONSULTA OUC ON CON.CD_CONSULTA = OUC.CD_CONSULTA
LEFT JOIN VIP_PROCEDIMENTO PMT ON CON.CD_CONSULTA = PMT.CD_CONSULTA
LEFT JOIN VIP_USUARIO USU ON CON.CD_USUARIO = USU.CD_USUARIO
LEFT JOIN VSG_LOGRADOURO LGR ON GET_LOGRADOURO( USU.nm_logradouro, USU.cd_tipo_logradouro, USU.nu_logradouro_casa, USU.cd_bairro ) = LGR.CD_LOGRADOURO
LEFT JOIN VSC_UNIDADE UNI ON LGR.CD_UNIDADE = UNI.CD_UNIDADE
LEFT JOIN VSG_REGIAO REG ON UNI.CD_REGIAO = REG.CD_REGIAO




WHERE (NOF.DT_NOTIFICACAO BETWEEN TO_DATE('010113','DDMMYY') AND TO_DATE('311217','DDMMYY'))
AND (NOF.CD_CID BETWEEN 'A50' AND 'A539' OR NOF.CD_CID = 'O981')
AND CON.DT_AGENDA >= NOF.DT_NOTIFICACAO
AND UNI.NM_UNIDADE LIKE 'CS%'

ORDER BY CON.CD_USUARIO

)

GROUP BY DISTRITO, UNIDADE, AREA, USUARIO, DATA_NOTIF

)
GROUP BY DISTRITO, UNIDADE, AREA, EXTRACT(YEAR FROM DATA_NOTIF) ,EXTRACT(MONTH FROM DATA_NOTIF)

ORDER BY DISTRITO, UNIDADE, AREA, EXTRACT(YEAR FROM DATA_NOTIF) ,EXTRACT(MONTH FROM DATA_NOTIF)

;SPOOL OFF