SELECT REG.NM_REGIAO AS DISTRITO
      ,UNI.NM_UNIDADE AS UNIDADE
      ,LGR.CD_AREA AS AREA
      ,EXTRACT(YEAR FROM CON.DT_INICIO) AS ANO
      ,EXTRACT(MONTH FROM CON.DT_INICIO) AS MES
      ,COUNT(DISTINCT(CASE WHEN PRO.CD_ESPECIALIDADE IN ('152','165','5') THEN CON.CD_CONSULTA END)) AS CONSULTA_MED
      ,COUNT(DISTINCT(CASE WHEN PRO.CD_ESPECIALIDADE IN ('83','6') THEN CON.CD_CONSULTA END)) AS CONSULTA_ODO
      ,COUNT (DISTINCT(CASE WHEN PRO.CD_ESPECIALIDADE IN ('152','165','5') AND ENC.CD_ESPECIALIDADE_REFERENCIA NOT IN ('138','129','52','156','88','169','151','120','4','126','161','155','140','5','165','168','150','2','84','100','82','37','132','152','7','162','83','6','1','43','77','142','118','163','170')
            AND ENC.TP_ENCAMINHAMENTO = 'Normal' THEN CON.CD_CONSULTA END)) AS ENCS_MED
      ,COUNT(DISTINCT(CASE WHEN PRO.CD_ESPECIALIDADE IN ('83','6') AND ENC.CD_ESPECIALIDADE_REFERENCIA IN ('61','58','57','60','167','145','144') THEN ENC.CD_ENCAMINHAMENTO END)) AS ENCS_ODO
 
            
      

FROM VIA_CONSULTA CON
LEFT JOIN VIP_OUTRA_CONSULTA OUC ON CON.CD_CONSULTA = OUC.CD_CONSULTA
LEFT JOIN VIP_PROCEDIMENTO PMT ON CON.CD_CONSULTA = PMT.CD_CONSULTA
LEFT JOIN VIP_USUARIO USU ON CON.CD_USUARIO = USU.CD_USUARIO
LEFT JOIN VSG_LOGRADOURO LGR ON GET_LOGRADOURO( USU.nm_logradouro, USU.cd_tipo_logradouro, USU.nu_logradouro_casa, USU.cd_bairro ) = LGR.CD_LOGRADOURO
LEFT JOIN VSC_UNIDADE UNI ON LGR.CD_UNIDADE = UNI.CD_UNIDADE
LEFT JOIN VSG_REGIAO REG ON UNI.CD_REGIAO = REG.CD_REGIAO
LEFT JOIN VIC_PROFISSIONAL PRO ON CON.CD_PROFISSIONAL = PRO.CD_PROFISSIONAL
LEFT JOIN VSC_UNIDADE UNI2 ON TRUNC(CON.CD_CONSULTA / 10000000) = UNI2.CD_UNIDADE_INTERNO
LEFT JOIN VIP_ENCAMINHAMENTO_USUARIO ENC ON CON.CD_CONSULTA = ENC.CD_CONSULTA

WHERE (CON.DT_INICIO >= TRUNC(ADD_MONTHS(SYSDATE,-3),'MONTH') AND CON.DT_INICIO < TRUNC(SYSDATE,'MONTH'))
AND UNI.NM_UNIDADE LIKE 'CS%'
AND PRO.CD_ESPECIALIDADE IN ('152','165','5','6','83')
AND UNI2.NM_UNIDADE LIKE 'CS%'
AND (CON.CD_PROCEDIMENTO NOT IN ('908080','90078','90079','90159') OR OUC.CD_PROCEDIMENTO NOT IN ('908080','90078','90079','90159') OR PMT.CD_PROCEDIMENTO_BPA NOT IN ('908080','90078','90079'))

GROUP BY REG.NM_REGIAO
      ,UNI.NM_UNIDADE
      ,LGR.CD_AREA,EXTRACT(YEAR FROM CON.DT_INICIO)
      ,EXTRACT(MONTH FROM CON.DT_INICIO)

ORDER BY REG.NM_REGIAO
      ,UNI.NM_UNIDADE
      ,LGR.CD_AREA,EXTRACT(YEAR FROM CON.DT_INICIO)
      ,EXTRACT(MONTH FROM CON.DT_INICIO)

;
