SELECT DISTRITO
      ,UNIDADE
      ,AREA
      ,EXTRACT(YEAR FROM DIA_ATD) AS ANO
      ,EXTRACT(MONTH FROM DIA_ATD) AS MES
      ,COUNT(DISTINCT(USUARIO)) AS PESSOAS
      
FROM (


SELECT REG.NM_REGIAO AS DISTRITO
      ,UNI.NM_UNIDADE AS UNIDADE
      ,LGR.CD_AREA AS AREA
      ,CON.CD_USUARIO AS USUARIO
      ,TO_DATE(CON.DT_INICIO, 'dd/mm/RRRR') AS DIA_ATD
    

            
      
FROM VIP_USUARIO USU
LEFT JOIN VIA_CONSULTA CON ON USU.CD_USUARIO = CON.CD_USUARIO
LEFT JOIN VIP_OUTRA_CONSULTA OUC ON CON.CD_CONSULTA = OUC.CD_CONSULTA
LEFT JOIN VIP_PROCEDIMENTO PMT ON CON.CD_CONSULTA = PMT.CD_CONSULTA
LEFT JOIN VSG_LOGRADOURO LGR ON GET_LOGRADOURO( USU.nm_logradouro, USU.cd_tipo_logradouro, USU.nu_logradouro_casa, USU.cd_bairro ) = LGR.CD_LOGRADOURO
LEFT JOIN VSC_UNIDADE UNI ON LGR.CD_UNIDADE = UNI.CD_UNIDADE
LEFT JOIN VSG_REGIAO REG ON UNI.CD_REGIAO = REG.CD_REGIAO
LEFT JOIN VSC_UNIDADE UNI2 ON TRUNC(CON.CD_CONSULTA / 10000000) = UNI2.CD_UNIDADE_INTERNO
LEFT JOIN VIC_PROFISSIONAL PRO ON CON.CD_PROFISSIONAL = PRO.CD_PROFISSIONAL


WHERE (CON.dt_agenda >= TRUNC(ADD_MONTHS(SYSDATE,-3),'MONTH') AND CON.dt_agenda < TRUNC(SYSDATE,'MONTH'))
AND (CON.CD_PROCEDIMENTO NOT IN ('908080') OR OUC.CD_PROCEDIMENTO NOT IN ('908080') OR PMT.CD_PROCEDIMENTO_BPA NOT IN ('908080'))
AND USU.FL_SEXO = 'F'
AND (TRUNC(MONTHS_BETWEEN(CON.DT_INICIO,USU.DT_NASCIMENTO) / 12) BETWEEN 25 AND 64)
AND PRO.CD_ESPECIALIDADE IN (2,5,152,165)
AND UNI2.NM_UNIDADE LIKE 'CS%'
AND UNI.NM_UNIDADE LIKE 'CS%'
AND CON.CD_CONSULTA IS NOT NULL

)

GROUP BY DISTRITO
      ,UNIDADE
      ,AREA
      ,EXTRACT(YEAR FROM DIA_ATD)
      ,EXTRACT(MONTH FROM DIA_ATD)
      
ORDER BY DISTRITO
      ,UNIDADE
      ,AREA
      ,EXTRACT(YEAR FROM DIA_ATD)
      ,EXTRACT(MONTH FROM DIA_ATD)





;
