SELECT DISTRITO
      ,UNIDADE
      ,AREA
      ,EXTRACT(YEAR FROM DIA) AS ANO
      ,EXTRACT(MONTH FROM DIA) AS MES
      ,COUNT(DISTINCT(CASE WHEN (ESPECIALIDADE IN ('2','152','165','5')) THEN USUARIO END)) AS USU_MED_ENF
      ,COUNT(DISTINCT(CASE WHEN (ESPECIALIDADE IN ('2') ) THEN USUARIO END)) AS USU_ENF
      ,COUNT(DISTINCT(CASE WHEN (ESPECIALIDADE IN ('152','165','5')) THEN USUARIO END)) AS USU_MED
      ,COUNT(DISTINCT(CASE WHEN (ESPECIALIDADE IN ('83','6') ) THEN USUARIO END)) AS USU_ODO
      ,COUNT(DISTINCT(USUARIO)) AS USU_TODOS_SERVICOS

FROM ((

SELECT REG.NM_REGIAO AS DISTRITO
      ,UNI.NM_UNIDADE AS UNIDADE
      ,LGR.CD_AREA AS AREA
      ,CON.CD_USUARIO AS USUARIO
      ,CON.DT_INICIO AS DIA
      ,PRO.CD_ESPECIALIDADE AS ESPECIALIDADE

            
      
FROM VIA_CONSULTA CON
LEFT JOIN VIC_PROFISSIONAL PRO ON CON.CD_PROFISSIONAL = PRO.CD_PROFISSIONAL
LEFT JOIN VIP_OUTRA_CONSULTA OUC ON CON.CD_CONSULTA = OUC.CD_CONSULTA
LEFT JOIN VIP_PROCEDIMENTO PMT ON CON.CD_CONSULTA = PMT.CD_CONSULTA
LEFT JOIN VIP_USUARIO USU ON CON.CD_USUARIO = USU.CD_USUARIO
LEFT JOIN VSG_LOGRADOURO LGR ON GET_LOGRADOURO( USU.nm_logradouro, USU.cd_tipo_logradouro, USU.nu_logradouro_casa, USU.cd_bairro ) = LGR.CD_LOGRADOURO
LEFT JOIN VSC_UNIDADE UNI ON LGR.CD_UNIDADE = UNI.CD_UNIDADE
LEFT JOIN VSG_REGIAO REG ON UNI.CD_REGIAO = REG.CD_REGIAO
LEFT JOIN VSC_UNIDADE UNI2 ON TRUNC(CON.CD_CONSULTA / 10000000) = UNI2.CD_UNIDADE_INTERNO

WHERE (CON.DT_INICIO >= TRUNC(ADD_MONTHS(SYSDATE,-3),'MONTH') AND CON.DT_INICIO < TRUNC(SYSDATE,'MONTH'))
AND UNI2.NM_UNIDADE LIKE 'CS%'
AND UNI.NM_UNIDADE LIKE 'CS%'
AND (CON.CD_PROCEDIMENTO NOT IN ('908080','90079','90159','90078') OR OUC.CD_PROCEDIMENTO NOT IN ('908080','90079','90159','90078') OR PMT.CD_PROCEDIMENTO_BPA NOT IN ('908080','90079','90159','90078'))
)
UNION ALL
(
SELECT REG.NM_REGIAO AS DISTRITO
      ,UNI.NM_UNIDADE AS UNIDADE
      ,LGR.CD_AREA AS AREA
      ,RIT.CD_USUARIO AS USUARIO
      ,RIE.DT_ENTREGA AS DIA
      ,10010 AS ESPECIALIDADE

FROM VIF_RECEITA_ITEM_ENTREGA RIE
LEFT JOIN VIF_RECEITA_ITEM RIT ON RIE.CD_ITEM_RECEITA = RIT.CD_ITEM_RECEITA
LEFT JOIN VIP_USUARIO USU ON RIT.CD_USUARIO = USU.CD_USUARIO
LEFT JOIN VSG_LOGRADOURO LGR ON GET_LOGRADOURO( USU.nm_logradouro, USU.cd_tipo_logradouro, USU.nu_logradouro_casa, USU.cd_bairro ) = LGR.CD_LOGRADOURO
LEFT JOIN VSC_UNIDADE UNI ON LGR.CD_UNIDADE = UNI.CD_UNIDADE
LEFT JOIN VSG_REGIAO REG ON UNI.CD_REGIAO = REG.CD_REGIAO
LEFT JOIN VSC_UNIDADE UNI2 ON TRUNC(RIT.CD_ITEM_RECEITA / 10000000) = UNI2.CD_UNIDADE_INTERNO

WHERE (RIE.DT_ENTREGA >= TRUNC(ADD_MONTHS(SYSDATE,-3),'MONTH') AND RIE.DT_ENTREGA < TRUNC(SYSDATE,'MONTH'))
AND RIE.DT_ENTREGA IS NOT NULL
AND UNI2.NM_UNIDADE LIKE 'CS%'
AND UNI.NM_UNIDADE LIKE 'CS%'
)
)
   
            
GROUP BY DISTRITO
      ,UNIDADE
      ,AREA
      ,EXTRACT(YEAR FROM DIA)
      ,EXTRACT(MONTH FROM DIA)

ORDER BY DISTRITO
      ,UNIDADE
      ,AREA
      ,EXTRACT(YEAR FROM DIA)
      ,EXTRACT(MONTH FROM DIA)
      
;