spool /home/plan/ShinyApps/aps/producao/base_de_dados/extraidas/atd_inad_upa/atd_inad_upa.csv
set sqlformat csv  
set feedback off  
    
SELECT DISTRITO       ,UNIDADE       ,AREA       ,EXTRACT(YEAR FROM DATA_ATEND) AS ANO       ,EXTRACT(MONTH FROM DATA_ATEND) AS MES       ,COUNT(CONSULTA) AS QTDE_ATEND         FROM (  SELECT REG.NM_REGIAO AS DISTRITO       ,UNI.nm_unidade AS UNIDADE       ,LGR.cd_area AS AREA       ,CON.CD_CONSULTA AS CONSULTA       ,CON.dt_AGENDA AS DATA_ATEND       ,PRI.nm_prioridade AS CLASSIFICACAO_DE_RISCO   FROM VIA_CONSULTA CON LEFT JOIN VIP_USUARIO USU ON CON.CD_USUARIO = USU.CD_USUARIO LEFT JOIN VSG_LOGRADOURO LGR ON GET_LOGRADOURO( USU.nm_logradouro, USU.cd_tipo_logradouro, USU.nu_logradouro_casa, USU.cd_bairro ) = LGR.CD_LOGRADOURO LEFT JOIN VSC_UNIDADE UNI ON LGR.CD_UNIDADE = UNI.CD_UNIDADE LEFT JOIN VSG_REGIAO REG ON UNI.CD_REGIAO = REG.CD_REGIAO LEFT JOIN VIC_PRIORIDADE_ATENDIMENTO PRI ON CON.CD_PRIORIDADE_TRIAGEM = PRI.CD_PRIORIDADE LEFT JOIN VIC_PROFISSIONAL PRO ON CON.CD_PROFISSIONAL = PRO.CD_PROFISSIONAL   WHERE (CON.dt_agenda >= TRUNC(ADD_MONTHS(SYSDATE,-3),'MONTH') AND CON.dt_agenda < TRUNC(SYSDATE,'MONTH')) AND CON.dt_agenda >= TO_DATE(TO_CHAR(CON.DT_AGENDA, 'DD/MM/YYYY') || ' ' || '08:00:00', 'DD/MM/YYYY HH24:MI:SS') AND CON.dt_agenda <= TO_DATE(TO_CHAR(CON.DT_AGENDA, 'DD/MM/YYYY') || ' ' || '16:59:59', 'DD/MM/YYYY HH24:MI:SS') AND PRI.NU_PRIORIDADE IN (3,4) AND TRUNC(CON.CD_CONSULTA / 10000000) IN (109,55) AND TO_CHAR(CON.DT_AGENDA, 'DY','NLS_DATE_LANGUAGE=AMERICAN') NOT IN ('SAT', 'SUN')  AND PRO.CD_ESPECIALIDADE IN (2) AND UNI.CD_UNIDADE IS NOT NULL  ORDER BY DISTRITO,UNIDADE,AREA  )  GROUP BY DISTRITO       ,UNIDADE       ,AREA       ,EXTRACT(YEAR FROM DATA_ATEND)       ,EXTRACT(MONTH FROM DATA_ATEND)  ORDER BY DISTRITO       ,UNIDADE       ,AREA       ,EXTRACT(YEAR FROM DATA_ATEND)       ,EXTRACT(MONTH FROM DATA_ATEND)  ;

spool off 

exit 
 
EOF
